# Generated by Django 4.2.2 on 2023-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='static/shop_images/image1.png', upload_to='static/shop_images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='total_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
