# Generated by Django 4.2.2 on 2023-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_alter_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
