# Generated by Django 4.2.2 on 2023-06-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_alter_shop_shop_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
