# Generated by Django 4.2.2 on 2023-06-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_rename_owner_shop_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
