# Generated by Django 4.2.2 on 2023-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_rename_owner_id_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='build/static/products_images/image1.png', upload_to='build/static/products_images/'),
        ),
        migrations.DeleteModel(
            name='ProductPicture',
        ),
    ]
