# Generated by Django 4.2.2 on 2023-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_product_image_delete_productpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='build/static/product_pictures/profile.png', null=True, upload_to='build/static/product_pictures/'),
        ),
    ]
