# Generated by Django 4.2.2 on 2023-06-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentshop',
            name='report_count',
            field=models.BooleanField(default=False),
        ),
    ]
