# Generated by Django 4.2.2 on 2023-06-30 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall', '0015_alter_commentshop_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentshop',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommentShopReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('Inappropriate Content', 'Inappropriate Content'), ('Spam', 'Spam'), ('Other', 'Other')], max_length=50)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.commentproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
