# Generated by Django 4.2.2 on 2023-07-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_product_stripe_price_id_product_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_price_id',
            new_name='price_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_id',
            new_name='product_id',
        ),
    ]
