# Generated by Django 4.2.2 on 2023-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_rename_stripe_price_id_product_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='prfile_image',
            field=models.ImageField(default='build/static/shop_images/image1.png', upload_to='build/static/shop_images/'),
        ),
    ]
