# Generated by Django 4.2.2 on 2023-07-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_shop_prfile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='prfile_image',
            new_name='profile_image',
        ),
    ]
